In [234]:
import numpy as np

In [235]:
arr = np.arange(0,11)

In [236]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [237]:
arr[8]

np.int64(8)

In [238]:
arr[1:5]

array([1, 2, 3, 4])

In [239]:
arr[:5]

array([0, 1, 2, 3, 4])

In [240]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [241]:
# Broadcasting
arr[0:5] = 100
 

In [242]:
arr

# In this example, what we've done with broadcasting is that we've replaced the first 5 indeces with the value of "100"

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [243]:
arr = np.arange(0,11)

In [244]:
slice_of_arr = arr[0:5]

In [245]:
slice_of_arr[:] = 99

# What this does is that it takes the slice of array that we did beforehand, and then broadcasted the values of that slice with the number "99"

In [246]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [247]:
arr

# and then here our main array takes the value of that sliced array and is then now implemented onto the current array.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [248]:
# In order to avoid having this to happen. We can create a copy of our original array by using the .copy() function.

arr_copy = arr.copy()

In [249]:
arr_copy[:] = 100

# here is the syntax for when we reassigned the values of our array copy.

In [250]:
# But here in this syntax we have the original array as is.

# copy of array with new assigned values.
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [251]:
# Here is our original array.
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [252]:
arr_2d = np.array([[5, 10, 15],[20, 25, 30],[5, 10, 15]])

In [253]:
arr_2d.shape

(3, 3)

In [254]:
arr_2d.shape[0]

3

In [255]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [256]:
# conditional selection

arr = np.arange(1, 11)

In [257]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [258]:
arr > 4

# this codeblock will check our array for values that are greater than "4", if it is it wil convert the values in our array to boolean values.
# Hence, returning the following output:

# array([False, False, False, False,  True,  True,  True,  True,  True, True])
# In this case, any number that is lower than "4", will convert the value to "False", and if the value of our array is greater than "4", it will convert the value to True.

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [259]:
# if we want to get the values that were all turned to "True" use the following codeblock:

bool_arr = arr>4

In [260]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[bool_arr]

# end of codeblock
 
# Here by using the original array(since this contains the numeric values of the bool_arr), and by using the bool_arr variable to return us the
# numeric values of the original array variable. Hence displaying the following output.

# array([ 5,  6,  7,  8,  9, 10])

array([ 5,  6,  7,  8,  9, 10])