In [114]:
import numpy as np

In [115]:
arr = np.arange(0,11)

In [116]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
arr[8]

np.int64(8)

In [118]:
arr[1:5]

array([1, 2, 3, 4])

In [119]:
arr[:5]

array([0, 1, 2, 3, 4])

In [120]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
# Broadcasting
arr[0:5] = 100
 

In [122]:
arr

# In this example, what we've done with broadcasting is that we've replaced the first 5 indeces with the value of "100"

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [123]:
arr = np.arange(0,11)

In [124]:
slice_of_arr = arr[0:5]

In [125]:
slice_of_arr[:] = 99

# What this does is that it takes the slice of array that we did beforehand, and then broadcasted the values of that slice with the number "99"

In [126]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [127]:
arr

# and then here our main array takes the value of that sliced array and is then now implemented onto the current array.

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [128]:
# In order to avoid having this to happen. We can create a copy of our original array by using the .copy() function.

arr_copy = arr.copy()

In [129]:
arr_copy[:] = 100

# here is the syntax for when we reassigned the values of our array copy.

In [131]:
# But here in this syntax we have the original array as is.

# copy of array with new assigned values.
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [132]:
# Here is our original array.
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])