In [27]:
import numpy as np

In [28]:
# converting a python list to a numpy array

a = [1, 2, 3, 4, 5]

# to convert a python list to a numpy array, we use the np.array() function
b = np.array(a)

In [29]:
b
# output: array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [30]:
type(b)

numpy.ndarray

In [31]:
my_matrix = [[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]]]

In [32]:
my_matrix= np.array(my_matrix)

my_matrix[0][1][2]

np.int64(6)

In [33]:
np.arange(0, 11 + 2, 2)

#np.arange(start, stop, step)
# start: starting value of the sequence
# stop: end value of the sequence (exclusive)
# step: difference between each two consecutive values in the sequence

array([ 0,  2,  4,  6,  8, 10, 12])

In [34]:
big_shape = np.zeros((50,30))
# np.zeros() creates an array filled with zeros, the values are of float data type by default
# the shape of the array is defined by the shape parameter, which is a tuple representing the dimensions of the array
# syntax: np.zeros(shape, dtype=float, order='C')


In [35]:
import pandas as pd

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [36]:
ones_shape = np.ones((4,5))

ones_shape = pd.DataFrame(ones_shape)

ones_shape

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0

In [37]:
np.linspace(0, 10, num=21)
# syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# start: starting value of the sequence
# stop: end value of the sequence
# Return evenly spaced numbers over a specified interval.
# dtype by default is float


array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [38]:
len(np.linspace(0, 10, num=21))
# this returns the length of the array generated by np.linspace()

21

In [39]:
np.eye(10)
# numpy identity matrix of size 10x10
# np.eye() creates a 2-D array with ones on the diagonal and zeros elsewhere
# 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [65]:
# Random Library

np.random.rand(3,10)

array([[0.94962531, 0.66054571, 0.29005426, 0.45539456, 0.5379216 ,
        0.44347921, 0.41190498, 0.48534818, 0.97586468, 0.61692393],
       [0.82396838, 0.77398881, 0.85912261, 0.04179478, 0.41964284,
        0.10928077, 0.35416596, 0.71789114, 0.37114347, 0.72330225],
       [0.62585436, 0.15238035, 0.43314327, 0.27353886, 0.21743171,
        0.21135507, 0.86528127, 0.56787519, 0.20088433, 0.55252122]])