In [111]:
import numpy as np

In [112]:
# converting a python list to a numpy array

a = [1, 2, 3, 4, 5]

# to convert a python list to a numpy array, we use the np.array() function
b = np.array(a)

In [113]:
b
# output: array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [114]:
type(b)

numpy.ndarray

In [115]:
my_matrix = [[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]]]

In [116]:
my_matrix= np.array(my_matrix)

my_matrix[0][1][2]

np.int64(6)

In [117]:
np.arange(0, 11 + 2, 2)

#np.arange(start, stop, step)
# start: starting value of the sequence
# stop: end value of the sequence (exclusive)
# step: difference between each two consecutive values in the sequence

array([ 0,  2,  4,  6,  8, 10, 12])

In [118]:
big_shape = np.zeros((50,30))
# np.zeros() creates an array filled with zeros, the values are of float data type by default
# the shape of the array is defined by the shape parameter, which is a tuple representing the dimensions of the array
# syntax: np.zeros(shape, dtype=float, order='C')


In [119]:
import pandas as pd

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [120]:
ones_shape = np.ones((4,5))

ones_shape = pd.DataFrame(ones_shape)

ones_shape

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0  1.0
3  1.0  1.0  1.0  1.0  1.0

In [ ]:
# syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# start: starting value of the sequence
# stop: end value of the sequence
# Return evenly spaced numbers over a specified interval.
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])