In [58]:
import numpy as np

In [59]:
# converting a python list to a numpy array

a = [1, 2, 3, 4, 5]

# to convert a python list to a numpy array, we use the np.array() function
b = np.array(a)

In [60]:
b
# output: array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [61]:
type(b)

numpy.ndarray

In [62]:
my_matrix = [[[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]], [[1,2,3], [4,5,6], [7,8,9]],[[1,2,3], [4,5,6], [7,8,9]]]

In [63]:
my_matrix= np.array(my_matrix)

my_matrix[0][1][2]

np.int64(6)

In [64]:
np.arange(0, 11 + 2, 2)

#np.arange(start, stop, step)
# start: starting value of the sequence
# stop: end value of the sequence (exclusive)
# step: difference between each two consecutive values in the sequence

array([ 0,  2,  4,  6,  8, 10, 12])

In [ ]:
big_shape = np.zeros((50,30))

np.zeros((2,2))
# np.zeros creates an array (depending on specified shape), also defining its dimensions, filled with zeros, which in turn is considered as a tuple.
# Note: Keep in mind that the "zeros" data type are floats.

array([[0., 0.],
       [0., 0.]])

In [67]:
import pandas as pd

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows',None)

In [ ]:
ones_shape = np.ones((2,5))

ones_shape = pd.DataFrame(ones_shape)

ones_shape

0    1    2    3    4
0  1.0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0  1.0