In [83]:
import numpy as np

In [84]:
arr = np.arange(0, 11)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Broadcasting



In [86]:
arr[:5] = 100

In [87]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [88]:
arr = np.arange(0, 25)

In [89]:
slice_of_arr = arr[:5]

In [90]:
# slice_of_arr = 99

In [91]:
slice_of_arr[:] = 99

In [92]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [93]:
arr_copy = arr.copy()

In [94]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [95]:
arr_2d = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [96]:
arr_2d.shape

(3, 3)

In [97]:
arr_2d[2][2]

np.int64(9)

In [98]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [99]:
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea3121efac5dd3338c280ff10068f9c8

import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])


In [100]:
dice_rolls > 2

array([ True, False,  True, False,  True, False, False,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
        True, False,  True,  True,  True,  True, False,  True,  True,
        True,  True])

bool_arr = dice_rolls > 2
type(len(dice_rolls[bool_arr]))

In [101]:
import numpy as np

In [102]:
arr = np.arange(0,10)

In [103]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Other Numpy Array functions

In [105]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])